config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get :dashboard, to: 'pages#dashboard'
  patch 'booking_requests/:id', to: "booking_requests#accept", as: :accept_booking
  delete 'booking_requests/:id', to: "booking_requests#decline", as: :decline_booking
  get 'booking_request/:id/confirm', to: "booking_requests#confirm", as: :confirm_booking
  get 'booking_request/:id/pay', to: "booking_requests#pay", as: :pay_booking

  resources :chat_rooms, only: :index
  # Users are created by Devise
  resources :flats, only: %i[new create show index edit update] do
    # A Booking Request needs a User and a Flat.
    resources :booking_requests, only: %i[new create destroy]
    # Reviews don't need to be nested if the creation and view are on the show page of the booking request
    # Chats only need of a flat id
    resources :chat_rooms, only: %i[new create show destroy] do
      resources :messages, only: :create
    end
    # Messages are created by the chat so don't need a route.
    resources :amenities, only: %i[new create]
    resources :available_months, only: %i[new create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :booking_requests, only: :show do
    resources :reviews, only: :create
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :chat_rooms
  has_many :booking_requests
  has_many :available_months, dependent: :destroy
  has_many :messages, through: :chatrooms
  has_many :reviews, through: :booking_requests
  has_many :amenities, dependent: :destroy
  has_many_attached :photos
  validates :address, presence: true
  validates :price, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :city, presence: true
  #validates :photos, presence: true
  validates :name, presence: true

  geocoded_by :full_street_address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_date_price_direction_city,
    against: [ :address, :price, :name ],
    using: {
      tsearch: { prefix: true }
    }

  def available?(date_s)
    month = available_months.find_by(month_year: date_s)
    return month.nil? ? false : !month.taken
  end

  def available_between?(date_s, date_e)
    months = available_months.select do |am|
      am.month_year.to_date >= date_s.to_date && am.month_year.to_date <= date_e.to_date && !am.taken
    end
    return months.any?
  end

  def edit_amenities(g_amenities_ids)
    puts "enter amenities-------"
    g_amenities_ids.inspect
    amenis = []
    GeneralAmenity.all.each do |ga|
      on_flat = amenities.find_by(title: ga.title)
      puts "on flat: #{on_flat&.title}"
      unless g_amenities_ids.include?(ga.id.to_s) && on_flat
        if g_amenities_ids.include?(ga.id.to_s)
          a = Amenity.new(title: ga.title, icon_class: ga.icon_class, flat_id: id)
          puts a
          amenis << a
        elsif on_flat
          puts "destroying #{on_flat.id}"
          on_flat.destroy!
        end
      end
    end
    Amenity.transaction do
      amenis.each do |a|
        puts "saving amenities"
        a.save!
      end
    end

  end

  def review_average
    sum = 0.0
    reviews.each do |r|
      sum+= r.rating
    end
    return reviews.any? ? (sum.to_f/reviews.size).round(1) : 0
  end

  def full_street_address
    [address, city].compact.join(', ')
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :authenticate_user!

  def index
    # Searching against available months and (location, name or address)
    if params[:query].present? && params[:search].present? && params[:search][:start_month].present? && params[:search][:end_month].present?
      @flats = Flat.joins(:available_months)
        .select("flats.*")
        .where("month_year >= :start_date AND month_year <= :end_date AND taken = :taken AND city ILIKE :location OR address ILIKE :location OR name ILIKE :location",
        {start_date: params[:search][:start_month], end_date: params[:search][:end_month], taken: false, location: "%#{params[:query]}%"})
        .group("flats.id")
    # Searching against available months
    elsif params[:search].present? && params[:search][:start_month].present? && params[:search][:end_month].present?
      @flats = Flat.joins(:available_months)
        .select("flats.*")
        .where("month_year >= :start_date AND month_year <= :end_date AND taken = :taken",
        {start_date: params[:search][:start_month], end_date: params[:search][:end_month], taken: false})
        .group("flats.id")
    # Search agains city, name, address
    elsif params[:query].present?
      sql_query = " \
        flats.city ILIKE :query \
        OR flats.address ILIKE :query \
        OR flats.name ILIKE :query
      "
      @flats = Flat.where(sql_query, query: "%#{params[:query]}%")
    # Show all flats (when no queries)
    else
      @flats = Flat.all
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @reviews = @flat.reviews
    @amenities = @flat.amenities
    @user = current_user if user_signed_in?
    @booking = BookingRequest.new
    @available_month = AvailableMonth.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to @flat
    else
      render :new
    end
  end

  def new
    if current_user.flats.any?
      redirect_to flat_path(current_user.flats.first)
    else
      @flat = Flat.new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
    redirect_to flat_path(@flat) unless @flat.user = current_user
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      flash[:alert] = "Error while updating, try again later"
      redirect_to flat_path(@flat)
    end
  end

  def available_between?(date_s, date_e)
    months = available_months.select do |am|
      am.month_year.to_date >= date_s.to_date && am.month_year.to_date <= date_e.to_date && !am.taken
    end
    return months.any?
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :price, :description, :city, photos: [])
  end
end

app/views/flats/_month_p.html.erb
<% if month.taken %>
  <p class="py-1 px-2 btn-sb rounded-pill border-0 f14W mt-3 ml-1">
  <%= month.month_year.to_date.strftime("%b %y") %>
  </p>
<% else  %>
  <p class="py-1 px-2 btn-db rounded-pill border-0 f14W mt-3 ml-1">
  <%= month.month_year.to_date.strftime("%b %y") %>
  </p>
<%end %>

app/views/flats/edit.html.erb
<%= render 'components/flat_form', flat: @flat %>

app/views/flats/index.html.erb
<%= render 'components/search_bar' %>
<div class="">
  <div class="cards">
    <% @flats.each do |flat| %>
      <% unless flat.user_id == current_user.id %>
        <%=link_to flat_path(flat), class: "text-decoration-none" do%>
          <div class="card-trip">
            <%= cl_image_tag flat.photos.first.key %>
            <div class="card-trip-infos">
              <div>

                <h2 style="text-decoration:none;" id="pL"><%=flat.city %></h2>
                <p id="pL"><%=flat.address %></p>
              </div>
              <div>
              <h2 class="card-trip-pricing"><%=flat.price.to_s + " €/month"%></h2>

              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :description %>
  <%= f.input :price, input_html: { min: '0', step: 'any' } %>
  <%= f.input :photos, as: :file %>
  <%= f.submit "Add flat", class: "btn btn-success rounded-pill mt-4 mb-3 mr-3" %>
<% end %>

app/views/flats/show.html.erb
<%# main start %>
<div class="container pT" data-controller= "show" data-show-hide-class="d-none">
  <div class="">
    <div class="">
      <p class="f26"><%= @flat.name %></p>
      <div class="titleFlex">
        <div class="flex justify-content-between">
          <p class="f14"><%= image_tag "star.png", class: "pT5"%> &nbsp; <%= @flat.review_average%> - <%= @flat.reviews.count%> reviews &nbsp;📍<%= @flat.city %>, <%= @flat.address %> &nbsp; 💶&nbsp;<%= @flat.price %>€/month</p>
        </div>
        <% if current_user == @flat.user %>
          <div style="padding-bottom:10px;">
            <%= link_to edit_flat_path(@flat) do %>
              <span class="iconify" data-icon="clarity:note-edit-line" style="color: #a1a1aa; margin-right:10px;" data-width="32"></span>
            <% end %>
            <%= link_to new_flat_amenity_path(@flat) do %>
              <span class="iconify" data-icon="carbon:add-alt" style="color: #a1a1aa; margin-right:18px;" data-width="32"></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <%# Images wrapper start %>
  <div class="imgContainer">
      <%# Main pic start %>
    <div>
      <%= cl_image_tag @flat.photos.first.key, class: "mainImage" %>
    </div>
      <%# Main pic end %>
      <%# Secondary pics start %>
    <div class="grid">
      <% @flat.photos.each_with_index do |photo, i| %>
        <% unless i == 0%>
          <%= cl_image_tag photo.key, class: "secondaryImage" %>
        <% end %>
      <% end %>
    </div>
      <%# Secondary pics end %>
  </div>
  <div class="d-flex justify-content-end px-3" data-show-target="dates">
    <% @flat.available_months.each do |month| %>
       <%= render 'flats/month_p', month: month %>
    <% end %>
  </div>
  <%# Images wrapper end %>

  <%# Wrapper amenities description form starts %>
  <div class="grid2">
    <%# Amenities start %>
    <div class="pT wAmenities mr-5">
      <p class="f24">What the place offers</p>
      <div class="amenitiesGrid pT2 pB30 borderB">
        <% @flat.amenities.each do |amenity| %>
          <p class="f16"><span class="iconify" data-icon=<%=amenity.icon_class%> style="color: #2c364c; font-size: 28px;"></span> <%= amenity.title %></p>
        <% end %>
      </div>
      <%# Amenities end %>
      <%# Description start %>
      <div class="pTB borderB">
        <p class="f16" style="padding-top:30px; padding-bottom:30px; margin-bottom:0;"><%= @flat.description %></p>
      </div>
      <%# Description end %>
      <%# Reviews start %>
      <%= render 'components/reviews' %>
      <%# Reviews end %>
    </div>

    <%# Wrapper amenities description form end %>

    <%# Booking start %>
    <%  unless current_user == @flat.user %>
      <div class="form m0 w250 pB30 mt-5 shadow">
        <p class="f20 pB" style="padding-left: 5px;">Your Hometastic Stay</p>
        <%= simple_form_for [ @flat, @booking ] do |f| %>
          <%= f.input :month_request, as: :string, required: true, placeholder:'select date', wrapper_html: {class:"form-month"}, input_html: {class: "datepicker"} %>
          <br>
          <%= f.submit "Send a request to this Flat", class: "btn-lb rounded-pill border-0 w-100 py-3 f14W" %>
        <% end %>
        <%= link_to "Chat with the owner", flat_chat_rooms_path(@flat), method: :post, class: "btn-db rounded-pill border-0 w-100 mt-3 py-3 f14W" %>
      </div>

    <% else %>
      <div class="column-container pAddDates" style="margin-left: 110px;">
        <button class="display-available mt-5" data-show-target="displayer" data-action="click->show#display"
          >Add available month</button>
        <div class="form m0 pB30 mt-5 shadow d-none wForm" data-show-target="month">
          <%= render 'components/available_form', flat: @flat, available_month: @available_month %>
        </div>
      </div>

    <% end  %>
  </div>
</div>